### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by IDDQDesnik** [advancedmonitoring/SDDLViewer#1]
Приложение падает при попытке доступа к каталогу без нужных прав.

`Приложение: SDDLViewer.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: System.UnauthorizedAccessException
   в System.Security.AccessControl.Win32.GetSecurityInfo(System.Security.AccessControl.ResourceType, System.String, System.Runtime.InteropServices.SafeHandle, System.Security.AccessControl.AccessControlSections, System.Security.AccessControl.RawSecurityDescriptor ByRef)
   в System.Security.AccessControl.NativeObjectSecurity.CreateInternal(System.Security.AccessControl.ResourceType, Boolean, System.String, System.Runtime.InteropServices.SafeHandle, System.Security.AccessControl.AccessControlSections, Boolean, ExceptionFromErrorCode, System.Object)
   в System.Security.AccessControl.FileSystemSecurity..ctor(Boolean, System.String, System.Security.AccessControl.AccessControlSections, Boolean)
   в System.Security.AccessControl.DirectorySecurity..ctor(System.String, System.Security.AccessControl.AccessControlSections)
   в SDDLViewer.Logic.Model.UpdateDirectory(System.String)
   в SDDLViewer.Logic.Model.DirectoryFill(System.Object)
   в System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   в System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   в System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   в System.Threading.ThreadHelper.ThreadStart(System.Object)`

**Comment by xi-tauw** [comment]
Спасибо за ишью, при случае я добавлю обработку исключений.

**Comment by xi-tauw** [comment]
Добавил try-catch, обновил релиз
